
# blog
services:
    blog_db:
        platform: 'linux/amd64'
        container_name: blog_db
        command: --max_allowed_packet=32505856
        image: mariadb
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - ./docker/database/data:/var/lib/mysql:z
volumes:
  db:
    driver: local
